### PR TITLE
[MM-45155] Add support for using plugin when MM is served under a subpath

### LINKED ISSUE #112: Calls Plugin not working within subdirectory
We run Mattermost in a subdirectory, but apparently the Calls plugin can't handle it. No user icons are displayed and screen sharing, for example, refers to the main domain and ignores the subdirectory.

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

Fixes #112 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-45155

### CODE REVIEW

File: webapp/src/websocket.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ import {logWarn, logErr} from './log';
 
 export default class WebSocketClient extends EventEmitter {
     private ws: WebSocket | null;
-    private seqNo = 0;
+    private seqNo = 1;
```
Comment (cpoile) [inline webapp/src/websocket.ts:10]: just curious what this is for?

**Review by cpoile — APPROVED** [review]
👍

File: webapp/src/websocket.ts (hunk 1 above)
Comment (streamer45) [reply webapp/src/websocket.ts:10]: The change was to conform to what's expected on the server side as the zero value is treated as invalid. I found this during debugging but it doesn't affect anything at the moment. The sequence number is used by the server to figure out which events to resend to the client in case of an unexpected reconnection.

Comment (streamer45) [reply webapp/src/websocket.ts:10]: Sorry, went into "teaching mode" there :sweat_smile:
